import { Activity, Ambulance, Clock3, Cpu, Signal, Timer, TrafficCone } from "lucide-react";
import { motion } from "framer-motion";
import { useDashboard } from "../contexts/DashboardContext";

function Kpi({ icon: Icon, label, value, accent = "text-emerald-300" }: { icon: typeof Activity; label: string; value: string | number; accent?: string }) { return <motion.article initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-white/10 bg-[#161b22] p-4"><Icon size={18} className={accent} /><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-400">{label}</p></motion.article>; }

export function DashboardPage() {
  const { state } = useDashboard();
  const signals = state?.signals;
  const mission = state?.mission;
  return <section><div className="mb-7"><p className="text-sm text-emerald-300">LIVE MISSION CONTROL</p><h1 className="mt-1 text-3xl font-semibold">Traffic at a glance</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={TrafficCone} label="Tracked vehicles" value={state?.metrics.total_vehicles ?? 0} /><Kpi icon={Signal} label="Current green" value={signals?.current_green ?? "—"} accent="text-amber-300" /><Kpi icon={Timer} label="Signal countdown" value={signals ? `${signals.remaining_seconds}s` : "—"} accent="text-sky-300" /><Kpi icon={Ambulance} label="Emergency status" value={mission?.status ?? "IDLE"} accent="text-rose-300" /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-xl border border-white/10 bg-[#161b22] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Current AI decision</h2><Cpu size={19} className="text-emerald-300" /></div>{state?.ai_decision ? <div className="mt-6 grid gap-4 sm:grid-cols-3"><div><p className="text-sm text-slate-400">Prioritized road</p><p className="mt-1 text-2xl font-semibold">{state.ai_decision.road}</p></div><div><p className="text-sm text-slate-400">Recommended green</p><p className="mt-1 text-2xl font-semibold">{state.ai_decision.green_time}s</p></div><div><p className="text-sm text-slate-400">Confidence</p><p className="mt-1 text-2xl font-semibold">{state.ai_decision.confidence}%</p></div><p className="sm:col-span-3 rounded-lg bg-white/5 p-3 text-sm text-slate-300">{state.ai_decision.reason}</p></div> : <p className="mt-5 text-sm text-slate-400">Waiting for the first traffic observation.</p>}</article><article className="rounded-xl border border-white/10 bg-[#161b22] p-5"><div className="flex items-center gap-2"><Activity size={19} className="text-sky-300" /><h2 className="font-semibold">Recent operations</h2></div><div className="mt-4 space-y-3">{state?.logs.slice(-4).reverse().map((event) => <div key={`${event.timestamp}-${event.event}`} className="border-l-2 border-emerald-400/60 pl-3"><p className="text-sm">{event.event}</p><p className="text-xs text-slate-500">{new Date(event.timestamp).toLocaleTimeString()}</p></div>) ?? <p className="text-sm text-slate-400">Connecting to the command center…</p>}</div></article></div><article className="mt-5 rounded-xl border border-white/10 bg-[#161b22] p-5"><div className="flex items-center gap-2"><Clock3 size={19} className="text-amber-300" /><h2 className="font-semibold">Road pressure</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.values(state?.analytics.roads ?? {}).map((road) => <div key={road.road} className="rounded-lg bg-white/5 p-4"><p className="text-sm text-slate-400">{road.road}</p><p className="mt-2 text-xl font-semibold">{road.vehicle_count} vehicles</p><p className="mt-1 text-xs text-emerald-300">{road.congestion} · score {road.density_score}</p></div>)}</div></article></section>;
}
